---
swagger: "2.0"
info:
  description: "Defines API to service logic interpreter,This module contains a collection\
    \ of generally useful derived\nYANG data types.\n\nCopyright (c) 2013 IETF Trust\
    \ and the persons identified as\nauthors of the code.  All rights reserved.\n\n\
    Redistribution and use in source and binary forms, with or\nwithout modification,\
    \ is permitted pursuant to, and subject\nto the license terms contained in, the\
    \ Simplified BSD License\nset forth in Section 4.c of the IETF Trust's Legal Provisions\n\
    Relating to IETF Documents\n(http://trustee.ietf.org/license-info).\n\nThis version\
    \ of this YANG module is part of RFC 6991; see\nthe RFC itself for full legal\
    \ notices.,This module contains a collection of generally useful derived\nYANG\
    \ data types for Internet addresses and related things.\n\nCopyright (c) 2013\
    \ IETF Trust and the persons identified as\nauthors of the code.  All rights reserved.\n\
    \nRedistribution and use in source and binary forms, with or\nwithout modification,\
    \ is permitted pursuant to, and subject\nto the license terms contained in, the\
    \ Simplified BSD License\nset forth in Section 4.c of the IETF Trust's Legal Provisions\n\
    Relating to IETF Documents\n(http://trustee.ietf.org/license-info).\n\nThis version\
    \ of this YANG module is part of RFC 6991; see\nthe RFC itself for full legal\
    \ notices."
  version: "1.1.0-SNAPSHOT"
  title: "SLI-API,ietf-yang-types,ietf-inet-types API"
consumes:
- "application/json"
- "application/xml"
produces:
- "application/json"
- "application/xml"
paths:
  /config/SLI-API:test-results/:
    get:
      tags:
      - "SLI-API"
      description: "returns sli.api.TestResults"
      parameters: []
      responses:
        400:
          description: "Internal error"
        200:
          description: "sli.api.TestResults"
          responseSchema:
            originalRef: "#/definitions/sli.api.TestResults"
            $ref: "#/definitions/sli.api.TestResults"
          schema:
            originalRef: "#/definitions/sli.api.TestResults"
            $ref: "#/definitions/sli.api.TestResults"
    post:
      tags:
      - "SLI-API"
      description: "creates sli.api.TestResults"
      parameters:
      - in: "body"
        name: "sli.api.TestResults.body-param"
        description: "sli.api.TestResults to be added to list"
        required: false
        schema:
          originalRef: "#/definitions/sli.api.TestResults"
          $ref: "#/definitions/sli.api.TestResults"
      responses:
        400:
          description: "Internal error"
        201:
          description: "Object created"
        409:
          description: "Object already exists"
    put:
      tags:
      - "SLI-API"
      description: "creates or updates sli.api.TestResults"
      parameters:
      - in: "body"
        name: "sli.api.TestResults.body-param"
        description: "sli.api.TestResults to be added or updated"
        required: false
        schema:
          originalRef: "#/definitions/sli.api.TestResults"
          $ref: "#/definitions/sli.api.TestResults"
      responses:
        400:
          description: "Internal error"
        201:
          description: "Object created"
        204:
          description: "Object modified"
    delete:
      tags:
      - "SLI-API"
      description: "removes sli.api.TestResults"
      parameters: []
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /config/SLI-API:test-results/SLI-API:test-result/:
    post:
      description: "creates sli.api.testresults.TestResult"
      parameters:
      - in: "body"
        name: "sli.api.testresults.TestResult.body-param"
        description: "sli.api.testresults.TestResult to be added to list"
        required: false
        schema:
          originalRef: "#/definitions/sli.api.testresults.TestResult"
          $ref: "#/definitions/sli.api.testresults.TestResult"
      responses:
        400:
          description: "Internal error"
        201:
          description: "Object created"
        409:
          description: "Object already exists"
  /config/SLI-API:test-results/SLI-API:test-result/{test-identifier}/:
    get:
      tags:
      - "SLI-API"
      description: "returns sli.api.testresults.TestResult"
      parameters:
      - name: "test-identifier"
        in: "path"
        description: "Id of test-result"
        required: true
        type: "string"
      responses:
        400:
          description: "Internal error"
        200:
          description: "sli.api.testresults.TestResult"
          responseSchema:
            originalRef: "#/definitions/sli.api.testresults.TestResult"
            $ref: "#/definitions/sli.api.testresults.TestResult"
          schema:
            originalRef: "#/definitions/sli.api.testresults.TestResult"
            $ref: "#/definitions/sli.api.testresults.TestResult"
    post:
      tags:
      - "SLI-API"
      description: "creates sli.api.testresults.TestResult"
      parameters:
      - name: "test-identifier"
        in: "path"
        description: "Id of test-result"
        required: true
        type: "string"
      - in: "body"
        name: "sli.api.testresults.TestResult.body-param"
        description: "sli.api.testresults.TestResult to be added to list"
        required: false
        schema:
          originalRef: "#/definitions/sli.api.testresults.TestResult"
          $ref: "#/definitions/sli.api.testresults.TestResult"
      responses:
        400:
          description: "Internal error"
        201:
          description: "Object created"
        409:
          description: "Object already exists"
    put:
      tags:
      - "SLI-API"
      description: "creates or updates sli.api.testresults.TestResult"
      parameters:
      - name: "test-identifier"
        in: "path"
        description: "Id of test-result"
        required: true
        type: "string"
      - in: "body"
        name: "sli.api.testresults.TestResult.body-param"
        description: "sli.api.testresults.TestResult to be added or updated"
        required: false
        schema:
          originalRef: "#/definitions/sli.api.testresults.TestResult"
          $ref: "#/definitions/sli.api.testresults.TestResult"
      responses:
        400:
          description: "Internal error"
        201:
          description: "Object created"
        204:
          description: "Object modified"
    delete:
      tags:
      - "SLI-API"
      description: "removes sli.api.testresults.TestResult"
      parameters:
      - name: "test-identifier"
        in: "path"
        description: "Id of test-result"
        required: true
        type: "string"
      responses:
        400:
          description: "Internal error"
        204:
          description: "Object deleted"
  /operational/SLI-API:test-results/:
    get:
      tags:
      - "SLI-API"
      description: "returns sli.api.TestResults"
      parameters: []
      responses:
        400:
          description: "Internal error"
        200:
          description: "sli.api.TestResults"
          responseSchema:
            originalRef: "#/definitions/sli.api.TestResults"
            $ref: "#/definitions/sli.api.TestResults"
          schema:
            originalRef: "#/definitions/sli.api.TestResults"
            $ref: "#/definitions/sli.api.TestResults"
  /operational/SLI-API:test-results/SLI-API:test-result/{test-identifier}/:
    get:
      tags:
      - "SLI-API"
      description: "returns sli.api.testresults.TestResult"
      parameters:
      - name: "test-identifier"
        in: "path"
        description: "Id of test-result"
        required: true
        type: "string"
      responses:
        400:
          description: "Internal error"
        200:
          description: "sli.api.testresults.TestResult"
          responseSchema:
            originalRef: "#/definitions/sli.api.testresults.TestResult"
            $ref: "#/definitions/sli.api.testresults.TestResult"
          schema:
            originalRef: "#/definitions/sli.api.testresults.TestResult"
            $ref: "#/definitions/sli.api.testresults.TestResult"
  /operations/SLI-API:execute-graph/:
    post:
      tags:
      - "SLI-API"
      parameters:
      - in: "body"
        name: "sli.api.executegraph.Input.body-param"
        required: false
        schema:
          properties:
            input:
              originalRef: "#/definitions/sli.api.executegraph.Input"
              $ref: "#/definitions/sli.api.executegraph.Input"
      responses:
        400:
          description: "Internal error"
        200:
          description: "Correct response"
          responseSchema:
            originalRef: "#/definitions/sli.api.ExecuteGraph"
            $ref: "#/definitions/sli.api.ExecuteGraph"
          schema:
            originalRef: "#/definitions/sli.api.ExecuteGraph"
            $ref: "#/definitions/sli.api.ExecuteGraph"
        201:
          description: "No response"
  /operations/SLI-API:healthcheck/:
    post:
      tags:
      - "SLI-API"
      parameters: []
      responses:
        400:
          description: "Internal error"
        200:
          description: "Correct response"
          responseSchema:
            originalRef: "#/definitions/sli.api.Healthcheck"
            $ref: "#/definitions/sli.api.Healthcheck"
          schema:
            originalRef: "#/definitions/sli.api.Healthcheck"
            $ref: "#/definitions/sli.api.Healthcheck"
        201:
          description: "No response"
  /operations/SLI-API:vlbcheck/:
    post:
      tags:
      - "SLI-API"
      parameters: []
      responses:
        400:
          description: "Internal error"
        200:
          description: "Correct response"
          responseSchema:
            originalRef: "#/definitions/sli.api.Vlbcheck"
            $ref: "#/definitions/sli.api.Vlbcheck"
          schema:
            originalRef: "#/definitions/sli.api.Vlbcheck"
            $ref: "#/definitions/sli.api.Vlbcheck"
        201:
          description: "No response"
definitions:
  sli.api.ExecuteGraph:
    type: "object"
    properties:
      output:
        originalRef: "#/definitions/sli.api.ResponseFields"
        $ref: "#/definitions/sli.api.ResponseFields"
  sli.api.Healthcheck:
    type: "object"
    properties:
      output:
        originalRef: "#/definitions/sli.api.ResponseFields"
        $ref: "#/definitions/sli.api.ResponseFields"
  sli.api.ModeEnumeration:
    type: "string"
    enum:
    - "sync"
    - "async"
  sli.api.ParameterSetting:
    type: "object"
    properties:
      string-value:
        type: "string"
      boolean-value:
        type: "boolean"
      parameter-name:
        type: "string"
        description: "Parameter name"
      int-value:
        type: "integer"
        format: "int32"
  sli.api.ResponseFields:
    type: "object"
    properties:
      response-code:
        type: "string"
      response-message:
        type: "string"
      context-memory-json:
        type: "string"
      ack-final-indicator:
        type: "string"
  sli.api.TestResults:
    type: "object"
    properties:
      test-result:
        type: "array"
        items:
          originalRef: "#/definitions/sli.api.testresults.TestResult"
          $ref: "#/definitions/sli.api.testresults.TestResult"
  sli.api.Vlbcheck:
    type: "object"
    properties:
      output:
        originalRef: "#/definitions/sli.api.ResponseFields"
        $ref: "#/definitions/sli.api.ResponseFields"
  sli.api.executegraph.Input:
    type: "object"
    properties:
      mode:
        originalRef: "#/definitions/sli.api.ModeEnumeration"
        $ref: "#/definitions/sli.api.ModeEnumeration"
      module-name:
        type: "string"
      sli-parameter:
        type: "array"
        items:
          originalRef: "#/definitions/sli.api.ParameterSetting"
          $ref: "#/definitions/sli.api.ParameterSetting"
      rpc-name:
        type: "string"
  sli.api.testresults.TestResult:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          type: "string"
      test-identifier:
        type: "string"
